// This file is auto-generated by scripts/generate-validation.ts
// Do not edit manually - run 'npm run generate:validation' to regenerate
//
// This file encodes the CDK Props interface definitions into data structures that
// can be used at runtime to validate the attributes of incoming CDK Props objects,
// since the use of | any in the definitions prevents validation at transpilation time
//
// It also provides functions that will perform the validation on each Props object type
// parsed

// BucketProps from aws-cdk-lib/aws-s3
export const validBucketProps: Set<string> = new Set([
  'encryption',
  'encryptionKey',
  'enforceSSL',
  'bucketKeyEnabled',
  'bucketName',
  'removalPolicy',
  'autoDeleteObjects',
  'versioned',
  'objectLockEnabled',
  'objectLockDefaultRetention',
  'eventBridgeEnabled',
  'lifecycleRules',
  'transitionDefaultMinimumObjectSize',
  'websiteIndexDocument',
  'websiteErrorDocument',
  'websiteRedirect',
  'websiteRoutingRules',
  'accessControl',
  'publicReadAccess',
  'blockPublicAccess',
  'metrics',
  'cors',
  'serverAccessLogsBucket',
  'serverAccessLogsPrefix',
  'targetObjectKeyFormat',
  'inventories',
  'objectOwnership',
  'transferAcceleration',
  'notificationsHandlerRole',
  'notificationsSkipDestinationValidation',
  'intelligentTieringConfigurations',
  'minimumTLSVersion',
  'replicationRole',
  'replicationRules'
]);

// FunctionProps from aws-cdk-lib/aws-lambda
export const validFunctionProps: Set<string> = new Set([
  'runtime',
  'code',
  'handler'
]);

// RestApiProps from aws-cdk-lib/aws-apigateway
export const validRestApiProps: Set<string> = new Set([
  'binaryMediaTypes',
  'minimumCompressionSize',
  'minCompressionSize',
  'cloneFrom',
  'apiKeySourceType'
]);

// QueueProps from aws-cdk-lib/aws-sqs
export const validQueueProps: Set<string> = new Set([
  'queueName',
  'retentionPeriod',
  'deliveryDelay',
  'maxMessageSizeBytes',
  'receiveMessageWaitTime',
  'visibilityTimeout',
  'deadLetterQueue',
  'encryption',
  'encryptionMasterKey',
  'dataKeyReuse',
  'fifo',
  'contentBasedDeduplication',
  'deduplicationScope',
  'fifoThroughputLimit',
  'removalPolicy',
  'enforceSSL',
  'redriveAllowPolicy'
]);

// TableProps from aws-cdk-lib/aws-dynamodb
export const validTableProps: Set<string> = new Set([
  'tableName',
  'kinesisStream',
  'kinesisPrecisionTimestamp'
]);

// StreamProps from aws-cdk-lib/aws-kinesis
export const validStreamProps: Set<string> = new Set([
  'streamName',
  'retentionPeriod',
  'shardCount',
  'encryption',
  'encryptionKey',
  'streamMode',
  'removalPolicy',
  'shardLevelMetrics'
]);

// CfnDeliveryStreamProps from aws-cdk-lib/aws-kinesisfirehose
export const validCfnDeliveryStreamProps: Set<string> = new Set([
  'amazonOpenSearchServerlessDestinationConfiguration',
  'amazonopensearchserviceDestinationConfiguration',
  'databaseSourceConfiguration',
  'deliveryStreamEncryptionConfigurationInput',
  'deliveryStreamName',
  'deliveryStreamType',
  'directPutSourceConfiguration',
  'elasticsearchDestinationConfiguration',
  'extendedS3DestinationConfiguration',
  'httpEndpointDestinationConfiguration',
  'icebergDestinationConfiguration',
  'kinesisStreamSourceConfiguration',
  'mskSourceConfiguration',
  'redshiftDestinationConfiguration',
  's3DestinationConfiguration',
  'snowflakeDestinationConfiguration',
  'splunkDestinationConfiguration',
  'tags'
]);

// LogGroupProps from aws-cdk-lib/aws-logs
export const validLogGroupProps: Set<string> = new Set([
  'encryptionKey',
  'logGroupName',
  'dataProtectionPolicy',
  'deletionProtectionEnabled',
  'fieldIndexPolicies',
  'retention',
  'logGroupClass',
  'removalPolicy'
]);

// TopicProps from aws-cdk-lib/aws-sns
export const validTopicProps: Set<string> = new Set([
  'displayName',
  'topicName',
  'masterKey',
  'contentBasedDeduplication',
  'fifo',
  'loggingConfigs',
  'messageRetentionPeriodInDays',
  'enforceSSL',
  'signatureVersion',
  'tracingConfig',
  'fifoThroughputScope'
]);

// Shared validation implementation
// Target can be undefined - validation is skipped if target is undefined
export function ValidateProps(target: any | undefined, validProps: Set<string>, propsTypeName: string): void {
  if (!target) {
    return;
  }
  for (const key in target) {
    if (!validProps.has(key)) {
      throw new Error(`ERROR - ${key} is not a valid property of ${propsTypeName}`);
    }
  }
}

// Validation functions
export function ValidateBucketProps(target?: any): void {
  ValidateProps(target, validBucketProps, 'BucketProps');
}

export function ValidateFunctionProps(target?: any): void {
  ValidateProps(target, validFunctionProps, 'FunctionProps');
}

export function ValidateRestApiProps(target?: any): void {
  ValidateProps(target, validRestApiProps, 'RestApiProps');
}

export function ValidateQueueProps(target?: any): void {
  ValidateProps(target, validQueueProps, 'QueueProps');
}

export function ValidateTableProps(target?: any): void {
  ValidateProps(target, validTableProps, 'TableProps');
}

export function ValidateStreamProps(target?: any): void {
  ValidateProps(target, validStreamProps, 'StreamProps');
}

export function ValidateCfnDeliveryStreamProps(target?: any): void {
  ValidateProps(target, validCfnDeliveryStreamProps, 'CfnDeliveryStreamProps');
}

export function ValidateLogGroupProps(target?: any): void {
  ValidateProps(target, validLogGroupProps, 'LogGroupProps');
}

export function ValidateTopicProps(target?: any): void {
  ValidateProps(target, validTopicProps, 'TopicProps');
}
