/**
 *  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance
 *  with the License. A copy of the License is located at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  or in the 'license' file accompanying this file. This file is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES
 *  OR CONDITIONS OF ANY KIND, express or implied. See the License for the specific language governing permissions
 *  and limitations under the License.
 */

// This file is auto-generated by scripts/generate-validation.ts
// Do not edit manually - run 'npm run generate:validation' to regenerate
//
// This file encodes the CDK Props interface definitions into data structures that
// can be used at runtime to validate the attributes of incoming CDK Props objects,
// since the use of | any in the definitions prevents validation at transpilation time
//
// It also provides functions that will perform the validation on each Props object type
// parsed

import { Construct } from 'constructs';
import * as cdk from 'aws-cdk-lib';
import { DISABLE_PROPERTY_VALIDATION } from './constructs-feature-flags';

// ApplicationLoadBalancerProps from aws-cdk-lib/aws-elasticloadbalancingv2
export const validApplicationLoadBalancerProps: Set<string> = new Set([
  'clientKeepAlive',
  'crossZoneEnabled',
  'deletionProtection',
  'denyAllIgwTraffic',
  'desyncMitigationMode',
  'dropInvalidHeaderFields',
  'http2Enabled',
  'idleTimeout',
  'internetFacing',
  'ipAddressType',
  'loadBalancerName',
  'minimumCapacityUnit',
  'preserveHostHeader',
  'preserveXffClientPort',
  'securityGroup',
  'vpc',
  'vpcSubnets',
  'wafFailOpen',
  'xAmznTlsVersionAndCipherSuiteHeaders',
  'xffHeaderProcessingMode'
]);

// ApplicationListenerProps from aws-cdk-lib/aws-elasticloadbalancingv2
export const validApplicationListenerProps: Set<string> = new Set([
  'certificates',
  'defaultAction',
  'defaultTargetGroups',
  'loadBalancer',
  'mutualAuthentication',
  'open',
  'port',
  'protocol',
  'sslPolicy'
]);

// ContainerDefinitionProps from aws-cdk-lib/aws-ecs
export const validContainerDefinitionProps: Set<string> = new Set([
  'command',
  'containerName',
  'cpu',
  'credentialSpecs',
  'disableNetworking',
  'dnsSearchDomains',
  'dnsServers',
  'dockerLabels',
  'dockerSecurityOptions',
  'enableRestartPolicy',
  'entryPoint',
  'environment',
  'environmentFiles',
  'essential',
  'extraHosts',
  'gpuCount',
  'healthCheck',
  'hostname',
  'image',
  'inferenceAcceleratorResources',
  'interactive',
  'linuxParameters',
  'logging',
  'memoryLimitMiB',
  'memoryReservationMiB',
  'portMappings',
  'privileged',
  'pseudoTerminal',
  'readonlyRootFilesystem',
  'restartAttemptPeriod',
  'restartIgnoredExitCodes',
  'secrets',
  'startTimeout',
  'stopTimeout',
  'systemControls',
  'taskDefinition',
  'ulimits',
  'user',
  'versionConsistency',
  'workingDirectory'
]);

// FargateTaskDefinitionProps from aws-cdk-lib/aws-ecs
export const validFargateTaskDefinitionProps: Set<string> = new Set([
  'cpu',
  'enableFaultInjection',
  'ephemeralStorageGiB',
  'executionRole',
  'family',
  'memoryLimitMiB',
  'pidMode',
  'proxyConfiguration',
  'runtimePlatform',
  'taskRole',
  'volumes'
]);

// FargateServiceProps from aws-cdk-lib/aws-ecs
export const validFargateServiceProps: Set<string> = new Set([
  'assignPublicIp',
  'availabilityZoneRebalancing',
  'bakeTime',
  'canaryConfiguration',
  'capacityProviderStrategies',
  'circuitBreaker',
  'cloudMapOptions',
  'cluster',
  'deploymentAlarms',
  'deploymentController',
  'deploymentStrategy',
  'desiredCount',
  'enableECSManagedTags',
  'enableExecuteCommand',
  'healthCheckGracePeriod',
  'lifecycleHooks',
  'linearConfiguration',
  'maxHealthyPercent',
  'minHealthyPercent',
  'platformVersion',
  'propagateTags',
  'securityGroups',
  'serviceConnectConfiguration',
  'serviceName',
  'taskDefinition',
  'taskDefinitionRevision',
  'volumeConfigurations',
  'vpcSubnets'
]);

// LambdaRestApiProps from aws-cdk-lib/aws-apigateway
export const validLambdaRestApiProps: Set<string> = new Set([
  'apiKeySourceType',
  'binaryMediaTypes',
  'cloneFrom',
  'cloudWatchRole',
  'cloudWatchRoleRemovalPolicy',
  'defaultCorsPreflightOptions',
  'defaultIntegration',
  'defaultMethodOptions',
  'deploy',
  'deployOptions',
  'description',
  'disableExecuteApiEndpoint',
  'domainName',
  'endpointConfiguration',
  'endpointExportName',
  'endpointTypes',
  'failOnWarnings',
  'handler',
  'integrationOptions',
  'minCompressionSize',
  'minimumCompressionSize',
  'parameters',
  'policy',
  'proxy',
  'restApiName',
  'retainDeployments'
]);

// RestApiProps from aws-cdk-lib/aws-apigateway
export const validRestApiProps: Set<string> = new Set([
  'apiKeySourceType',
  'binaryMediaTypes',
  'cloneFrom',
  'cloudWatchRole',
  'cloudWatchRoleRemovalPolicy',
  'defaultCorsPreflightOptions',
  'defaultIntegration',
  'defaultMethodOptions',
  'deploy',
  'deployOptions',
  'description',
  'disableExecuteApiEndpoint',
  'domainName',
  'endpointConfiguration',
  'endpointExportName',
  'endpointTypes',
  'failOnWarnings',
  'minCompressionSize',
  'minimumCompressionSize',
  'parameters',
  'policy',
  'restApiName',
  'retainDeployments'
]);

// DistributionProps from aws-cdk-lib/aws-cloudfront
export const validDistributionProps: Set<string> = new Set([
  'additionalBehaviors',
  'certificate',
  'comment',
  'defaultBehavior',
  'defaultRootObject',
  'domainNames',
  'enableIpv6',
  'enableLogging',
  'enabled',
  'errorResponses',
  'geoRestriction',
  'httpVersion',
  'logBucket',
  'logFilePrefix',
  'logIncludesCookies',
  'minimumProtocolVersion',
  'priceClass',
  'publishAdditionalMetrics',
  'sslSupportMethod',
  'webAclId'
]);

// UserPoolClientProps from aws-cdk-lib/aws-cognito
export const validUserPoolClientProps: Set<string> = new Set([
  'accessTokenValidity',
  'analytics',
  'authFlows',
  'authSessionValidity',
  'disableOAuth',
  'enablePropagateAdditionalUserContextData',
  'enableTokenRevocation',
  'generateSecret',
  'idTokenValidity',
  'oAuth',
  'preventUserExistenceErrors',
  'readAttributes',
  'refreshTokenRotationGracePeriod',
  'refreshTokenValidity',
  'supportedIdentityProviders',
  'userPool',
  'userPoolClientName',
  'writeAttributes'
]);

// DynamoEventSourceProps from aws-cdk-lib/aws-lambda-event-sources
export const validDynamoEventSourceProps: Set<string> = new Set([
  'batchSize',
  'bisectBatchOnError',
  'enabled',
  'filterEncryption',
  'filters',
  'maxBatchingWindow',
  'maxRecordAge',
  'metricsConfig',
  'onFailure',
  'parallelizationFactor',
  'provisionedPollerConfig',
  'reportBatchItemFailures',
  'retryAttempts',
  'startingPosition',
  'tumblingWindow'
]);

// CfnPipeProps from aws-cdk-lib/aws-pipes
export const validCfnPipeProps: Set<string> = new Set([
  'description',
  'desiredState',
  'enrichment',
  'enrichmentParameters',
  'kmsKeyIdentifier',
  'logConfiguration',
  'name',
  'roleArn',
  'source',
  'sourceParameters',
  'tags',
  'target',
  'targetParameters'
]);

// CfnDeliveryStreamProps from aws-cdk-lib/aws-kinesisfirehose
export const validCfnDeliveryStreamProps: Set<string> = new Set([
  'amazonOpenSearchServerlessDestinationConfiguration',
  'amazonopensearchserviceDestinationConfiguration',
  'databaseSourceConfiguration',
  'deliveryStreamEncryptionConfigurationInput',
  'deliveryStreamName',
  'deliveryStreamType',
  'directPutSourceConfiguration',
  'elasticsearchDestinationConfiguration',
  'extendedS3DestinationConfiguration',
  'httpEndpointDestinationConfiguration',
  'icebergDestinationConfiguration',
  'kinesisStreamSourceConfiguration',
  'mskSourceConfiguration',
  'redshiftDestinationConfiguration',
  's3DestinationConfiguration',
  'snowflakeDestinationConfiguration',
  'splunkDestinationConfiguration',
  'tags'
]);

// StreamProps from aws-cdk-lib/aws-kinesis
export const validStreamProps: Set<string> = new Set([
  'encryption',
  'encryptionKey',
  'removalPolicy',
  'retentionPeriod',
  'shardCount',
  'shardLevelMetrics',
  'streamMode',
  'streamName'
]);

// CfnJobProps from aws-cdk-lib/aws-glue
export const validCfnJobProps: Set<string> = new Set([
  'allocatedCapacity',
  'command',
  'connections',
  'defaultArguments',
  'description',
  'executionClass',
  'executionProperty',
  'glueVersion',
  'jobMode',
  'jobRunQueuingEnabled',
  'logUri',
  'maintenanceWindow',
  'maxCapacity',
  'maxRetries',
  'name',
  'nonOverridableArguments',
  'notificationProperty',
  'numberOfWorkers',
  'role',
  'securityConfiguration',
  'tags',
  'timeout',
  'workerType'
]);

// KinesisEventSourceProps from aws-cdk-lib/aws-lambda-event-sources
export const validKinesisEventSourceProps: Set<string> = new Set([
  'batchSize',
  'bisectBatchOnError',
  'enabled',
  'filterEncryption',
  'filters',
  'maxBatchingWindow',
  'maxRecordAge',
  'metricsConfig',
  'onFailure',
  'parallelizationFactor',
  'provisionedPollerConfig',
  'reportBatchItemFailures',
  'retryAttempts',
  'startingPosition',
  'startingPositionTimestamp',
  'tumblingWindow'
]);

// CfnCacheClusterProps from aws-cdk-lib/aws-elasticache
export const validCfnCacheClusterProps: Set<string> = new Set([
  'autoMinorVersionUpgrade',
  'azMode',
  'cacheNodeType',
  'cacheParameterGroupName',
  'cacheSecurityGroupNames',
  'cacheSubnetGroupName',
  'clusterName',
  'engine',
  'engineVersion',
  'ipDiscovery',
  'logDeliveryConfigurations',
  'networkType',
  'notificationTopicArn',
  'numCacheNodes',
  'port',
  'preferredAvailabilityZone',
  'preferredAvailabilityZones',
  'preferredMaintenanceWindow',
  'snapshotArns',
  'snapshotName',
  'snapshotRetentionLimit',
  'snapshotWindow',
  'tags',
  'transitEncryptionEnabled',
  'vpcSecurityGroupIds'
]);

// CfnIndexProps from aws-cdk-lib/aws-kendra
export const validCfnIndexProps: Set<string> = new Set([
  'capacityUnits',
  'description',
  'documentMetadataConfigurations',
  'edition',
  'name',
  'roleArn',
  'serverSideEncryptionConfiguration',
  'tags',
  'userContextPolicy',
  'userTokenConfigurations'
]);

// CfnDataSourceProps from aws-cdk-lib/aws-kendra
export const validCfnDataSourceProps: Set<string> = new Set([
  'customDocumentEnrichmentConfiguration',
  'dataSourceConfiguration',
  'description',
  'indexId',
  'languageCode',
  'name',
  'roleArn',
  'schedule',
  'tags',
  'type'
]);

// TopicProps from aws-cdk-lib/aws-sns
export const validTopicProps: Set<string> = new Set([
  'contentBasedDeduplication',
  'displayName',
  'enforceSSL',
  'fifo',
  'fifoThroughputScope',
  'loggingConfigs',
  'masterKey',
  'messageRetentionPeriodInDays',
  'signatureVersion',
  'topicName',
  'tracingConfig'
]);

// KeyProps from aws-cdk-lib/aws-kms
export const validKeyProps: Set<string> = new Set([
  'admins',
  'alias',
  'description',
  'enableKeyRotation',
  'enabled',
  'keySpec',
  'keyUsage',
  'multiRegion',
  'pendingWindow',
  'policy',
  'removalPolicy',
  'rotationPeriod'
]);

// VpcProps from aws-cdk-lib/aws-ec2
export const validVpcProps: Set<string> = new Set([
  'availabilityZones',
  'cidr',
  'createInternetGateway',
  'defaultInstanceTenancy',
  'enableDnsHostnames',
  'enableDnsSupport',
  'flowLogs',
  'gatewayEndpoints',
  'ipAddresses',
  'ipProtocol',
  'ipv6Addresses',
  'maxAzs',
  'natGatewayProvider',
  'natGatewaySubnets',
  'natGateways',
  'reservedAzs',
  'restrictDefaultSecurityGroup',
  'subnetConfiguration',
  'vpcName',
  'vpnConnections',
  'vpnGateway',
  'vpnGatewayAsn',
  'vpnRoutePropagation'
]);

// CfnModelProps from aws-cdk-lib/aws-sagemaker
export const validCfnModelProps: Set<string> = new Set([
  'containers',
  'enableNetworkIsolation',
  'executionRoleArn',
  'inferenceExecutionConfig',
  'modelName',
  'primaryContainer',
  'tags',
  'vpcConfig'
]);

// PrivateHostedZoneProps from aws-cdk-lib/aws-route53
export const validPrivateHostedZoneProps: Set<string> = new Set([
  'addTrailingDot',
  'comment',
  'queryLogsLogGroupArn',
  'vpc',
  'zoneName'
]);

// QueueProps from aws-cdk-lib/aws-sqs
export const validQueueProps: Set<string> = new Set([
  'contentBasedDeduplication',
  'dataKeyReuse',
  'deadLetterQueue',
  'deduplicationScope',
  'deliveryDelay',
  'encryption',
  'encryptionMasterKey',
  'enforceSSL',
  'fifo',
  'fifoThroughputLimit',
  'maxMessageSizeBytes',
  'queueName',
  'receiveMessageWaitTime',
  'redriveAllowPolicy',
  'removalPolicy',
  'retentionPeriod',
  'visibilityTimeout'
]);

// CfnWebACLProps from aws-cdk-lib/aws-wafv2
export const validCfnWebACLProps: Set<string> = new Set([
  'applicationConfig',
  'associationConfig',
  'captchaConfig',
  'challengeConfig',
  'customResponseBodies',
  'dataProtectionConfig',
  'defaultAction',
  'description',
  'name',
  'onSourceDDoSProtectionConfig',
  'rules',
  'scope',
  'tags',
  'tokenDomains',
  'visibilityConfig'
]);

// Shared validation implementation
// Scope is required for feature flag checking
// Target can be undefined - validation is skipped if target is undefined
export function ValidateProps(scope: Construct, target: any | undefined, validProps: Set<string>, propsTypeName: string): void {
  // Check if validation is disabled via feature flag
  if (cdk.FeatureFlags.of(scope).isEnabled(DISABLE_PROPERTY_VALIDATION)) {
    return;
  }
  if (!target) {
    return;
  }
  for (const key in target) {
    if (!validProps.has(key)) {
      throw new Error(`ERROR - ${key} is not a valid property of ${propsTypeName}`);
    }
  }
}

// Validation functions
export function ValidateApplicationLoadBalancerProps(scope: Construct, target?: any): void {
  ValidateProps(scope, target, validApplicationLoadBalancerProps, 'ApplicationLoadBalancerProps');
}

export function ValidateApplicationListenerProps(scope: Construct, target?: any): void {
  ValidateProps(scope, target, validApplicationListenerProps, 'ApplicationListenerProps');
}

export function ValidateContainerDefinitionProps(scope: Construct, target?: any): void {
  ValidateProps(scope, target, validContainerDefinitionProps, 'ContainerDefinitionProps');
}

export function ValidateFargateTaskDefinitionProps(scope: Construct, target?: any): void {
  ValidateProps(scope, target, validFargateTaskDefinitionProps, 'FargateTaskDefinitionProps');
}

export function ValidateFargateServiceProps(scope: Construct, target?: any): void {
  ValidateProps(scope, target, validFargateServiceProps, 'FargateServiceProps');
}

export function ValidateLambdaRestApiProps(scope: Construct, target?: any): void {
  ValidateProps(scope, target, validLambdaRestApiProps, 'LambdaRestApiProps');
}

export function ValidateRestApiProps(scope: Construct, target?: any): void {
  ValidateProps(scope, target, validRestApiProps, 'RestApiProps');
}

export function ValidateDistributionProps(scope: Construct, target?: any): void {
  ValidateProps(scope, target, validDistributionProps, 'DistributionProps');
}

export function ValidateUserPoolClientProps(scope: Construct, target?: any): void {
  ValidateProps(scope, target, validUserPoolClientProps, 'UserPoolClientProps');
}

export function ValidateDynamoEventSourceProps(scope: Construct, target?: any): void {
  ValidateProps(scope, target, validDynamoEventSourceProps, 'DynamoEventSourceProps');
}

export function ValidateCfnPipeProps(scope: Construct, target?: any): void {
  ValidateProps(scope, target, validCfnPipeProps, 'CfnPipeProps');
}

export function ValidateCfnDeliveryStreamProps(scope: Construct, target?: any): void {
  ValidateProps(scope, target, validCfnDeliveryStreamProps, 'CfnDeliveryStreamProps');
}

export function ValidateStreamProps(scope: Construct, target?: any): void {
  ValidateProps(scope, target, validStreamProps, 'StreamProps');
}

export function ValidateCfnJobProps(scope: Construct, target?: any): void {
  ValidateProps(scope, target, validCfnJobProps, 'CfnJobProps');
}

export function ValidateKinesisEventSourceProps(scope: Construct, target?: any): void {
  ValidateProps(scope, target, validKinesisEventSourceProps, 'KinesisEventSourceProps');
}

export function ValidateCfnCacheClusterProps(scope: Construct, target?: any): void {
  ValidateProps(scope, target, validCfnCacheClusterProps, 'CfnCacheClusterProps');
}

export function ValidateCfnIndexProps(scope: Construct, target?: any): void {
  ValidateProps(scope, target, validCfnIndexProps, 'CfnIndexProps');
}

export function ValidateCfnDataSourceProps(scope: Construct, target?: any): void {
  ValidateProps(scope, target, validCfnDataSourceProps, 'CfnDataSourceProps');
}

export function ValidateTopicProps(scope: Construct, target?: any): void {
  ValidateProps(scope, target, validTopicProps, 'TopicProps');
}

export function ValidateKeyProps(scope: Construct, target?: any): void {
  ValidateProps(scope, target, validKeyProps, 'KeyProps');
}

export function ValidateVpcProps(scope: Construct, target?: any): void {
  ValidateProps(scope, target, validVpcProps, 'VpcProps');
}

export function ValidateCfnModelProps(scope: Construct, target?: any): void {
  ValidateProps(scope, target, validCfnModelProps, 'CfnModelProps');
}

export function ValidatePrivateHostedZoneProps(scope: Construct, target?: any): void {
  ValidateProps(scope, target, validPrivateHostedZoneProps, 'PrivateHostedZoneProps');
}

export function ValidateQueueProps(scope: Construct, target?: any): void {
  ValidateProps(scope, target, validQueueProps, 'QueueProps');
}

export function ValidateCfnWebACLProps(scope: Construct, target?: any): void {
  ValidateProps(scope, target, validCfnWebACLProps, 'CfnWebACLProps');
}
