//!!NODE_ROOT <book>
[[aws-solutions-constructs]]
= AWS Solutions Constructs
:doctype: book
:toc: left
:icons: font
:experimental:
:idprefix:
:idseparator: -
:info_doctype: book
:info_title: AWS Solutions Constructs
:info_subtitle: AWS Solutions
:info_corpauthor: Amazon Web Services
:info_publisher: Amazon Web Services
:info_abstract: AWS Solutions Constructs (Constructs) is an open-source extension of the AWS Cloud Development Kit (AWS CDK) that \
            provides multi-service, well-architected patterns for quickly defining solutions in code \
            to create predictable and repeatable infrastructure.
:info_copyright: 2025 \
Amazon Web Services, Inc. and/or its affiliates. All rights reserved.
:info_legalnotice: Amazon's trademarks and trade dress may not be used in \
connection with any product or service that is not Amazon's, \
in any manner that is likely to cause confusion among customers, \
or in any manner that disparages or discredits Amazon. All other \
trademarks not owned by Amazon are the property of their respective \
owners, who may or may not be affiliated with, connected to, or \
sponsored by Amazon.

[abstract]
--
AWS Solutions Constructs (Constructs) is an open-source extension of the AWS Cloud Development Kit (AWS CDK) that provides multi-service, well-architected patterns for quickly defining solutions in code to create predictable and repeatable infrastructure.
--
:sectnums:

include::welcome.adoc[leveloffset=+1]


include::getting-started.adoc[leveloffset=+1]


include::api-reference.adoc[leveloffset=+1]


include::document-revisions.adoc[leveloffset=+1]


include::notices.adoc[leveloffset=+1]
