//!!NODE_ROOT <chapter>
[.topic]
[[notices,notices.title]]
= Notices
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:idprefix:
:idseparator: -
:sourcedir: .
:info_doctype: chapter
:info_title: Notices
:info_titleabbrev: Notices
:info_abstract: Notices

[abstract]
--
Notices
--

Customers are responsible for making their own independent assessment of the information in this document. This document: (a) is for informational purposes only, (b) represents current AWS product offerings and practices, which are subject to change without notice, and (c) does not create any commitments or assurances from AWS and its affiliates, suppliers or licensors. AWS products or services are provided "`as is`" without warranties, representations, or conditions of any kind, whether express or implied. The responsibilities and liabilities of AWS to its customers are controlled by AWS agreements, and this document is not part of, nor does it modify, any agreement between AWS and its customers.  

(C) 2020 Amazon Web Services, Inc. or its affiliates. All rights reserved. 