//!!NODE_ROOT <chapter>
[.topic]
[[welcome,welcome.title]]
= AWS Solutions Constructs
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:idprefix:
:idseparator: -
:sourcedir: .
:info_doctype: chapter
:info_title: AWS Solutions Constructs
:info_titleabbrev: Overview
:info_abstract: Overview

[abstract]
--
Overview
--

Publication date:  *May 2025* (xref:document-revisions[Document Revisions,linkend=document-revisions])

[[what-is-the-aws-solutions-constructs-library,what-is-the-aws-solutions-constructs-library.title]]
== What is AWS Solutions Constructs?

AWS Solutions Constructs (Constructs) is an open-source extension of the  https://aws.amazon.com/cdk/[AWS Cloud Development Kit (AWS CDK)] that provides multi-service, well-architected patterns for quickly defining solutions in code to create predictable and repeatable infrastructure. The goal is to accelerate the experience for developers to build solutions of any size using pattern-based definitions for their architecture. 

Use the AWS Solutions Constructs to define your solutions in a familiar programming language. The AWS Solutions Constructs supports TypeScript, JavaScript, Python, and Java at this time. 

To browse the full catalog of AWS Solutions Constructs patterns, https://aws.amazon.com/solutions/constructs/patterns/[click here]. 

[[why-use-the-aws-solutions-constructs-library,why-use-the-aws-solutions-constructs-library.title]]
== Why use AWS Solutions Constructs?

With the rate of innovation of cloud providers, knowing and understanding best practices and ensuring they are implemented correctly across your solution can be daunting. Constructs allows you to combine pre-built, well-architected patterns and use cases that perform common actions using cloud services in a scalable and secure manner. Because Constructs provides a library for modern programming languages, you can apply existing development skills and familiar tools to the task of building well-architected cloud infrastructure for your solutions.  

Other advantages of AWS Solutions Constructs include: 



* It is built upon the AWS Cloud Development Kit (AWS CDK) open source software development framework. 
* Use logic (if statements, for-loops, etc.) when defining your solution infrastructure. 
* Use object-oriented techniques to create a model of your system. 
* Define high level abstractions, share them, and publish them to your team, company, or community. 
* Organize your solutions into logical modules. 
* Share and reuse your solution as a library. 
* Test your infrastructure code using industry-standard protocols. 
* Use your existing code review workflow. 

The aim of AWS Solutions Constructs is to reduce the complexity and glue logic required when integrating common well-architected patterns to achieve your solution goals on AWS.  